# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict

  - repo: local
    hooks:

      ## Frontend Build Hook
      - id: build
        name: frontend_build
        entry: ./scripts/build.sh
        language: script
        # verbose: true
        pass_filenames: false
        always_run: true
        require_serial: true

      # Backend Unit Test Hook
      - id: test
        name: backend_test
        entry: ./scripts/test.sh
        language: script
        pass_filenames: false
        always_run: true
        require_serial: true

      ## Linting hooks
      - id: frontend_lint
        name: frontend_lint
        entry: ./scripts/lint.sh frontend
        language: script
        pass_filenames: false
        always_run: true
        require_serial: true

      - id: backend_lint
        name: backend_lint
        entry: ./scripts/lint.sh backend
        language: script
        pass_filenames: false
        always_run: true
        require_serial: true

      ## Formatting hooks
      - id: frontend_format
        name: frontend_format
        entry: ./scripts/format.sh frontend
        language: script
        pass_filenames: false
        always_run: true
        require_serial: true

      - id: backend_format
        name: backend_format
        entry: ./scripts/format.sh backend
        language: script
        pass_filenames: false
        always_run: true
        require_serial: true
